AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Calculator Lambda deployment

Resources:
  CalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: calculator.main.lambda_handler
      Runtime: python3.12
      CodeUri: .
      Timeout: 5
      MemorySize: 128
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /calculate
            Method: post
